# Generated by Django 2.2 on 2019-06-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('headimage', models.FileField(null=True, upload_to='tmp/', verbose_name='头像')),
                ('usernickname', models.CharField(default='', max_length=30, verbose_name='昵称')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('usersex', models.BooleanField(default=True, verbose_name='性别')),
                ('userage', models.CharField(default='', max_length=3, verbose_name='年龄')),
                ('userphone', models.CharField(max_length=13, verbose_name='手机号')),
                ('userEmail', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
