# Generated by Django 2.2 on 2019-06-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='userage',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
    ]
