# Generated by Django 2.2 on 2019-06-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_auto_20190626_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='userphone',
            field=models.CharField(max_length=13, verbose_name='手机号'),
        ),
    ]
